/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AdifPreviewModal: typeof import('./src/components/AdifPreviewModal.vue')['default']
    AuthGuard: typeof import('./src/components/AuthGuard.vue')['default']
    ButtonBar: typeof import('./src/components/ButtonBar.vue')['default']
    ContactsView: typeof import('./src/components/ContactsView.vue')['default']
    ExportFilterDialog: typeof import('./src/components/ExportFilterDialog.vue')['default']
    LoginForm: typeof import('./src/components/LoginForm.vue')['default']
    LogoutButton: typeof import('./src/components/LogoutButton.vue')['default']
    StatisticsPanel: typeof import('./src/components/StatisticsPanel.vue')['default']
    UserStatisticsPanel: typeof import('./src/components/UserStatisticsPanel.vue')['default']
    VanButton: typeof import('vant/es')['Button']
    VanCard: typeof import('vant/es')['Card']
    VanCellGroup: typeof import('vant/es')['CellGroup']
    VanCheckbox: typeof import('vant/es')['Checkbox']
    VanCollapse: typeof import('vant/es')['Collapse']
    VanCollapseItem: typeof import('vant/es')['CollapseItem']
    VanEmpty: typeof import('vant/es')['Empty']
    VanField: typeof import('vant/es')['Field']
    VanForm: typeof import('vant/es')['Form']
    VanIcon: typeof import('vant/es')['Icon']
    VanList: typeof import('vant/es')['List']
    VanLoading: typeof import('vant/es')['Loading']
    VanNavBar: typeof import('vant/es')['NavBar']
    VanPagination: typeof import('vant/es')['Pagination']
    VanPopup: typeof import('vant/es')['Popup']
    VanTab: typeof import('vant/es')['Tab']
    VanTabbar: typeof import('vant/es')['Tabbar']
    VanTabbarItem: typeof import('vant/es')['TabbarItem']
    VanTabs: typeof import('vant/es')['Tabs']
    VanTag: typeof import('vant/es')['Tag']
  }
}
