/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AdifPreviewModal: typeof import('./src/components/AdifPreviewModal.vue')['default']
    AuthGuard: typeof import('./src/components/AuthGuard.vue')['default']
    AwardProgressPanel: typeof import('./src/components/AwardProgressPanel.vue')['default']
    ButtonBar: typeof import('./src/components/ButtonBar.vue')['default']
    ChallengeView: typeof import('./src/components/ChallengeView.vue')['default']
    ChaserAdifPreviewModal: typeof import('./src/components/ChaserAdifPreviewModal.vue')['default']
    ContactsView: typeof import('./src/components/ContactsView.vue')['default']
    ExportFilterDialog: typeof import('./src/components/ExportFilterDialog.vue')['default']
    LeagueTablesPanel: typeof import('./src/components/LeagueTablesPanel.vue')['default']
    LoginForm: typeof import('./src/components/LoginForm.vue')['default']
    LogoutButton: typeof import('./src/components/LogoutButton.vue')['default']
    LogsView: typeof import('./src/components/LogsView.vue')['default']
    RecentActivationsPanel: typeof import('./src/components/RecentActivationsPanel.vue')['default']
    SpotsAlertsPanel: typeof import('./src/components/SpotsAlertsPanel.vue')['default']
    StatisticsPanel: typeof import('./src/components/StatisticsPanel.vue')['default']
    SummitsView: typeof import('./src/components/SummitsView.vue')['default']
    UserStatisticsPanel: typeof import('./src/components/UserStatisticsPanel.vue')['default']
    VanActionSheet: typeof import('vant/es')['ActionSheet']
    VanButton: typeof import('vant/es')['Button']
    VanCellGroup: typeof import('vant/es')['CellGroup']
    VanCheckbox: typeof import('vant/es')['Checkbox']
    VanCollapse: typeof import('vant/es')['Collapse']
    VanCollapseItem: typeof import('vant/es')['CollapseItem']
    VanDropdownItem: typeof import('vant/es')['DropdownItem']
    VanDropdownMenu: typeof import('vant/es')['DropdownMenu']
    VanEmpty: typeof import('vant/es')['Empty']
    VanField: typeof import('vant/es')['Field']
    VanForm: typeof import('vant/es')['Form']
    VanIcon: typeof import('vant/es')['Icon']
    VanLoading: typeof import('vant/es')['Loading']
    VanNavBar: typeof import('vant/es')['NavBar']
    VanPagination: typeof import('vant/es')['Pagination']
    VanPopup: typeof import('vant/es')['Popup']
    VanSearch: typeof import('vant/es')['Search']
    VanTab: typeof import('vant/es')['Tab']
    VanTabs: typeof import('vant/es')['Tabs']
    VanTag: typeof import('vant/es')['Tag']
  }
}
